sudo: required
language: python
python:
  - 3.7
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install: 
  - pip3 install -r requirements.txt
script: 
  - python3 -m pytest -v
  #- flake8
  - docker build -t app-server .
  - docker tag app-server registry.heroku.com/$HEROKU_APP_NAME/web
deploy:
  - provider: script
    script:
      docker push romicasal/app-server:production;
      docker push registry.heroku.com/$HEROKU_APP_NAME/web;
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master